name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 公開用ディレクトリを生成（リポ構成は不変）
      # 不要物は rsync の --exclude で除外
      - name: Prepare public directory (exclude non-public)
        run: |
          mkdir -p public
          rsync -av --delete \
            --exclude 'backup/' \
            --exclude '_archives/' \
            --exclude 'dev/' \
            --exclude '.github/' \
            --exclude '.vscode/' \
            --exclude '.idea/' \
            --exclude '.DS_Store' \
            --exclude 'dist/' \
            --exclude 'node_modules/' \
            --exclude 'scripts/' \
            --exclude 'tests/' --exclude 'test/' --exclude '*.spec.*' --exclude '*.test.*' \
            --exclude 'content/**/*.json' \
            --exclude '*.psd' --exclude '*.ai' --exclude '*.aep' --exclude '*.sketch' --exclude '*.fig' \
            --exclude '*.wav' --exclude '*.aiff' \
            --exclude 'secrets/' --exclude '*.key' --exclude '*.pem' --exclude '*.p12' --exclude '.env*' \
            ./ public/

      # 公開は public/ のみ
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
